# Generated by Django 5.1.2 on 2024-10-15 22:47

from django.db import migrations
from user.models import User
import json
import os


def create_base_users(a, b):
    # create superuser
    User.objects.create_superuser(**{
        'email': "admin@example.com",
        'password': "123",
        'name': "admin",
        'father_surname': "surname1",
        'mother_surname': "surname2",
        'age': "23",
        'phone_number': "6687654322",
    })

    # create staff user
    User.objects.create(**{
        'email': "staff@example.com",
        'password': "123",
        'name': "staff",
        'father_surname': "surname1",
        'mother_surname': "surname2",
        'age': "23",
        'phone_number': "6687654322",
        'is_staff': True,
    })

    migration_dir = os.path.dirname(__file__)
    file_path = os.path.join(migration_dir, '..', 'data', 'users.json')
    file_path = os.path.abspath(file_path)

    with open(file_path) as f:
        users_data = json.load(f)
        for user_data in users_data:
            User.objects.create(**user_data)


def delete_base_users():
    # create superuser
    User.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_users, delete_base_users)
    ]
